### ISSUE TITLE
Installation on iobroker 3.5.10 fails

### ISSUE THREAD

**Issue by hgehrts** [ioBroker/ioBroker.graphite#1]
I am trying to install the graphite adapter on the current iobroker release with no luck:

`root@iob-vm:~/.npm/_logs#  cat 2018-11-24T20_46_11_304Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/ioBroker/ioBroker.graphite/tarball/master',
1 verbose cli   '--production',
1 verbose cli   '--save',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker' ]
2 info using npm@6.4.1
3 info using node@v8.13.0
4 verbose npm-session d88676582355fe80
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://github.com/ioBroker/ioBroker.graphite/tarball/master 1031ms
8 silly pacote remote manifest for undefined@https://github.com/ioBroker/ioBroker.graphite/tarball/master fetched in 1039ms
9 timing stage:loadCurrentTree Completed in 2684ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 15ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 397ms
15 silly install loadAllDepsIntoIdealTree
16 timing stage:rollbackFailedOptional Completed in 0ms
17 timing stage:runTopLevelLifecycles Completed in 3098ms
18 silly saveTree iobroker.inst@1.1.2
18 silly saveTree ├─┬ iobroker.admin@3.5.10
18 silly saveTree │ ├─┬ body-parser@1.18.3
18 silly saveTree │ │ ├── bytes@3.0.0
....
18 silly saveTree   │ └── pause@0.0.1
18 silly saveTree   └── socket.io-client@1.7.2
19 verbose stack Error: Can't install https://github.com/ioBroker/ioBroker.graphite/tarball/master: Missing package name
19 verbose stack     at hasMinimumFields (/usr/lib/node_modules/npm/lib/install/validate-args.js:26:15)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at /usr/lib/node_modules/npm/lib/install/validate-args.js:16:5
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
19 verbose stack     at Array.forEach (<anonymous>)
19 verbose stack     at asyncMap (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
19 verbose stack     at module.exports (/usr/lib/node_modules/npm/lib/install/validate-args.js:15:3)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
19 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
19 verbose stack     at chain (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
19 verbose stack     at Installer.loadAllDepsIntoIdealTree (/usr/lib/node_modules/npm/lib/install.js:477:3)
19 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
20 verbose cwd /opt
21 verbose Linux 4.15.0-36-generic
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "https://github.com/ioBroker/ioBroker.graphite/tarball/master" "--production" "--save" "--prefix" "/opt/iobroker"
23 verbose node v8.13.0
24 verbose npm  v6.4.1
25 error Can't install https://github.com/ioBroker/ioBroker.graphite/tarball/master: Missing package name
26 verbose exit [ 1, true ]
root@iob-vm:~/.npm/_logs# `

**Comment by GermanBluefox** [comment]
As you can see this adapter is not maintained.

**Comment by GermanBluefox** [comment]
Use influxdb
